DROP TABLE USERS;
DROP TABLE ROLE;
DROP TABLE ORDER_ITENS;
DROP TABLE ORDER_C;
DROP TABLE PRODUCT;
DROP TABLE CUSTOMER;
DROP TABLE PHONE;
DROP TABLE ADDRESS;




CREATE TABLE PRODUCT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(200),
    UNITY_TYPE VARCHAR(10),
    UNITY_BUY_VALUE INT,
    UNITY_SELL_VALUE INT,
	QUANTITY INT(10)
    
);

CREATE TABLE ROLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(150)
);
 
CREATE TABLE USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(120),
    CPF INT(11) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    BORN_DATE DATE,
    ROLE_ID INT
);

ALTER TABLE USERS ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);


CREATE TABLE ADDRESS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STREET VARCHAR(200),
    NUMBER INT,
    ZIP_CEP INT(8),
    NEIGHBORHOOD VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100)
);

CREATE TABLE PHONE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DDD INT(2),
    NUMBER INT(9)
);

CREATE TABLE CUSTOMER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(150),
    CPF VARCHAR(11),
    EMAIL VARCHAR(150),
    PASSWORD VARCHAR(150),
    BORN_DATE DATE,
    ADDRESS_ID INT,
    PHONE_ID INT
);

ALTER TABLE CUSTOMER ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID);
ALTER TABLE CUSTOMER ADD FOREIGN KEY (PHONE_ID) REFERENCES PHONE (ID);

CREATE TABLE ORDER_C (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_OPENED_DATE DATE,
    ORDER_CLOSED_DATE DATE
);
ALTER TABLE ORDER_C ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);

CREATE TABLE ORDER_ITENS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    UNITY_VALUE INT NOT NULL,
    TOTAL_VALUE INT NOT NULL,
    QUANTITY INT
);

ALTER TABLE ORDER_ITENS ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE ORDER_ITENS ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDER_C (ID);



